export const FETCH_USER_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USERS_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';
//instanse product
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

//instanse cart
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';
export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST';
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';
export const CART_ADD_PRODUCT_FAILURE = 'CART_ADD_PRODUCT_FAILURE';
export const CART_UPDATE_ITEM_QUANTITY_REQUEST = 'CART_UPDATE_ITEM_QUANTITY_REQUEST';
export const CART_UPDATE_ITEM_QUANTITY_SUCCESS = 'CART_UPDATE_ITEM_QUANTITY_SUCCESS';
export const CART_UPDATE_ITEM_QUANTITY_FAILURE = 'CART_UPDATE_ITEM_QUANTITY_FAILURE';
export const REMOVE_FROM_CART_SUCCESS = '  REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_REQUEST = '  REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_FAILURE = '  REMOVE_FROM_CART_FAILURE';
export const CLEAR_CART = 'CLEAR_CART';
//instanse category
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILURE = 'ADD_FAVORITE_FAILURE';
export const REMOVE_FAVORITE_REQUEST = 'REMOVE_FAVORITE_REQUEST';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_FAILURE = 'REMOVE_FAVORITE_FAILURE';
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_REQUEST';
export const FETCH_FAVORITE_REQUEST = 'FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_FAILURE = 'FETCH_FAVORITE_FAILURE';
export const FETCH_FAVORITE_PRODUCTS_SUCCESS = 'FETCH_FAVORITE_PRODUCTS_REQUEST';
export const FETCH_FAVORITE_PRODUCTS_REQUEST = 'FETCH_FAVORITE_PRODUCTS_SUCCESS';
export const FETCH_FAVORITE_PRODUCTS_FAILURE = 'FETCH_FAVORITE_PRODUCTS_FAILURE';
